steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "gcr.io/treebeard-259315/image-builder"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--cache-from",
        "gcr.io/treebeard-259315/image-builder",
        "-t",
        "gcr.io/treebeard-259315/image-builder",
        ".",
      ]
images: ["gcr.io/treebeard-259315/image-builder"]
tags: ["builder"]
