name: Integration Test

on: [push]

jobs:
  conda:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install treebeard
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Test
        run: |
          cd integration-test/conda
          cp -R ../../treebeard-lib .
          treebeard run --watch --confirm

  virtualenv:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install treebeard
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Test
        run: |
          cd integration-test/virtualenv
          cp -R ../../treebeard-lib .
          treebeard run --watch --confirm

  dagster:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install treebeard
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Test
        run: |
          cd integration-test/dagster
          cp -R ../../treebeard-lib .
          treebeard run --watch --confirm

  failing_notebook:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install treebeard
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Test
        run: |
          cd integration-test/failing_notebook
          cp -R ../../treebeard-lib .
          python -m run_test
