name: Integration Test

on: [push]

jobs:
  conda:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pip install -e ./treebeard-lib
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Test
        run: |
          cd integration-test/conda
          cp -R ../../treebeard-lib .
          treebeard run --watch --confirm --local

  virtualenv:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pip install -e ./treebeard-lib
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Test
        run: |
          cd integration-test/virtualenv
          cp -R ../../treebeard-lib .
          treebeard run --watch --confirm
          wget https://api.treebeard.io/d8a0c5b6c9/virtualenv/cli/main.ipynb
          wget https://api.treebeard.io/d8a0c5b6c9/virtualenv/cli/another.ipynb
          wget https://api.treebeard.io/d8a0c5b6c9/virtualenv/cli/subdir/another.ipynb

  dagster:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pip install -e ./treebeard-lib
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Local
        run: |
          cd integration-test/dagster
          treebeard run --watch --confirm --local
      - name: Run Dockerless
        run: |
          cd integration-test/dagster
          pip install -r requirements.txt
          pip install treebeard
          treebeard run --dockerless --confirm

  failing_build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pip install -e ./treebeard-lib
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Buildtime Failure Test
        run: |
          cd integration-test/failing_build
          python -m run_test
  failing_notebook:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pip install -e ./treebeard-lib
      - name: Add credentials
        run: treebeard configure --email robot@treebeard.io --api_key ${{ secrets.TREEBEARD_API_KEY }}
      - name: Run Runtime Failure Test
        run: |

          cd integration-test/failing_notebook
          cp -R ../../treebeard-lib .
          python -m run_test
